### ISSUE TITLE
Vrpex

### ISSUE THREAD

**Issue by RenatoLNetto** [ImagicTheCat/FundamentalChemistry#1]
Hello. At base your vrpex has a broken file which is vrp_basicmenu. I went to put the blood bag for the players to heal more this breaking files.

**Comment by ImagicTheCat** [comment]
Well, that's a first for me, you're totally not in the right repository.

**Comment by RenatoLNetto** [comment]
Yes I just told you to know sorry for anything and Very good your brother
work. I hope it leaves the base update or you will not continue with the
project?

2018-06-26 4:35 GMT-03:00 Imagic <notifications@github.com>:
